sudo: required
services:
  - docker

before_install:
  - docker pull ps2docker/sdcc_docker

script:
  - docker run -v `pwd`:/subg_rfspy ps2docker/sdcc_docker /bin/sh -c "cd /subg_rfspy; make -f Makefile.test test"
  - docker run -v `pwd`:/subg_rfspy ps2docker/sdcc_docker /bin/sh -c "cd /subg_rfspy; make -f Makefile.spi1_alt2"
