SERIAL_TYPE := spi1_alt2
SERIAL_PARAMS := -DUSES_USART1_TX_ISR -DUSES_USART1_RX_ISR

BOARD_TYPE := MOCK_HARDWARE
BOARD_PARAMS :=

CC := gcc

CFLAGS+=-DRUN_TESTS

extra_modules = mock_hardware.rel tests.rel

include common.mk
